---
- name: redhat | installing pre-req packages
  yum:
    name: "{{ phpipam_redhat_packages }}"
    state: present
  become: true

- name: redhat | setting php timezone
  lineinfile:
    dest: /etc/php.ini
    line: "date.timezone = {{ phpipam_timezone }}"
  become: true
  notify: restart httpd
